---
version: '3.2'
services:
  plugin:
    image: ghcr.io/arcalot/arcaflow-plugin-pcp
    build: .
    volumes:
      - source: ./pcp_example.yaml
        target: /config/pcp_example.yaml
        type: bind