log:
  level: debug
    #deployer:
    #type: docker
    #deployment:
    #host:
    #NetworkMode: "host"
    #imagePullPolicy: IfNotPresent
deployer:
  type: kubernetes
  connection: !expr $.steps.kubeconfig.outputs.success.connection
  pod:
    metadata:
      namespace: default
      labels:
        arcaflow: pcp
    spec:
      pluginContainer:
        imagePullPolicy: Always
